-- =========================================================================
-- 公關品資源管理系統 (PRRMS) - Supabase 資料庫初始化 SQL 腳本
-- 請將此腳本複製並貼上到 Supabase 專案的 SQL Editor 中執行。
-- =========================================================================

-- 1. 建立商品主檔資料表 (items_list)
CREATE TABLE IF NOT EXISTS public.items_list (
    item_id text PRIMARY KEY,
    item_name text NOT NULL,
    inventory integer NOT NULL DEFAULT 0,
    price integer NOT NULL DEFAULT 0,
    image text
);

-- 2. 建立申請主檔資料表 (applications)
CREATE TABLE IF NOT EXISTS public.applications (
    task_id text PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    applicant_name text NOT NULL,
    staff_id text NOT NULL,
    status text NOT NULL DEFAULT 'SUBMITTED',
    applicant_phone text NOT NULL,
    applicant_email text NOT NULL,
    department text NOT NULL,
    cost_center text NOT NULL,
    reason text NOT NULL,
    total_amount numeric NOT NULL DEFAULT 0,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    reviewer text,
    review_comment text
);

-- 3. 建立申請明細資料表 (application_items)
CREATE TABLE IF NOT EXISTS public.application_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id text REFERENCES public.applications(task_id) ON DELETE CASCADE NOT NULL,
    item_id text NOT NULL,
    item_name text NOT NULL,
    unit_price integer NOT NULL DEFAULT 0,
    quantity integer NOT NULL DEFAULT 0,
    subtotal integer NOT NULL DEFAULT 0
);

-- 4. 建立庫存扣減 RPC 函數 (處理後台手動修改等防呆)
CREATE OR REPLACE FUNCTION public.decrease_inventory(item_ids text[], quantities integer[])
RETURNS void AS $$
DECLARE
    i integer;
BEGIN
    FOR i IN 1..array_length(item_ids, 1) LOOP
        -- 扣減庫存
        UPDATE public.items_list
        SET inventory = inventory - quantities[i]
        WHERE item_id = item_ids[i];
        
        -- 檢查是否庫存不足扣至負數，如果是則拋出異常阻斷交易
        IF EXISTS (SELECT 1 FROM public.items_list WHERE item_id = item_ids[i] AND inventory < 0) THEN
            RAISE EXCEPTION '商品 ID % 庫存不足，無法扣減！', item_ids[i];
        END IF;
    END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4-2. 建立原子性訂單提交 RPC 函數 (前台專用，主檔、明細與扣減庫存一鍵完成，確保交易完整性)
CREATE OR REPLACE FUNCTION public.create_promo_application(
    p_task_id text,
    p_applicant_name text,
    p_staff_id text,
    p_phone text,
    p_email text,
    p_department text,
    p_cost_center text,
    p_reason text,
    p_total_amount numeric,
    p_item_ids text[],
    p_item_names text[],
    p_prices integer[],
    p_quantities integer[]
)
RETURNS void AS $$
DECLARE
    i integer;
BEGIN
    -- 1. 新增申請主檔
    INSERT INTO public.applications (
        task_id, applicant_name, staff_id, status, applicant_phone, 
        applicant_email, department, cost_center, reason, total_amount
    ) VALUES (
        p_task_id, p_applicant_name, p_staff_id, 'SUBMITTED', p_phone, 
        p_email, p_department, p_cost_center, p_reason, p_total_amount
    );

    -- 2. 迴圈寫入明細並扣減庫存
    FOR i IN 1..array_length(p_item_ids, 1) LOOP
        -- 寫入明細
        INSERT INTO public.application_items (
            task_id, item_id, item_name, unit_price, quantity, subtotal
        ) VALUES (
            p_task_id, p_item_ids[i], p_item_names[i], p_prices[i], p_quantities[i], p_prices[i] * p_quantities[i]
        );

        -- 扣減庫存
        UPDATE public.items_list
        SET inventory = inventory - p_quantities[i]
        WHERE item_id = p_item_ids[i];
        
        -- 檢查庫存是否不足
        IF EXISTS (SELECT 1 FROM public.items_list WHERE item_id = p_item_ids[i] AND inventory < 0) THEN
            RAISE EXCEPTION '商品「%」目前庫存不足！', p_item_names[i];
        END IF;
    END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 5. 啟用資料表資料列層級安全性 (RLS) - 可選，建議啟用
ALTER TABLE public.items_list ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.application_items ENABLE ROW LEVEL SECURITY;

-- 建立允許匿名存取的安全原則 (Policies)
-- 5-1. 商品表：允許所有人讀取，允許所有人修改（前台扣庫存，後台修改商品）
CREATE POLICY "Allow public read" ON public.items_list FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.items_list FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.items_list FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.items_list FOR DELETE USING (true);

-- 5-2. 申請單主表：允許所有人寫入、所有人讀取（前台查詢與後台管理），允許更新與刪除
CREATE POLICY "Allow public select" ON public.applications FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.applications FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.applications FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.applications FOR DELETE USING (true);

-- 5-3. 申請明細表：允許所有人寫入、讀取、更新、刪除
CREATE POLICY "Allow public select" ON public.application_items FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.application_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.application_items FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.application_items FOR DELETE USING (true);

-- 6. 預塞部分商品測試資料 (可依需求刪除或執行)
INSERT INTO public.items_list (item_id, item_name, inventory, price, image) VALUES
('ID-001', '特製帆布袋', 50, 150, 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=300'),
('ID-002', '保溫隨行杯', 8, 350, 'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?auto=format&fit=crop&q=80&w=300'),
('ID-003', '質感原子筆', 120, 35, 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&q=80&w=300')
ON CONFLICT (item_id) DO NOTHING;
