-- =========================================================================
-- 公關品資源管理系統 (PRRMS) - Supabase 資料庫初始化 SQL 腳本
-- 請將此腳本複製並貼上到 Supabase 專案的 SQL Editor 中執行。
--
-- 💡 【歷史資料庫更新指令】若您的資料表已存在，請在 SQL Editor 執行以下指令更新欄位型態：
-- ALTER TABLE public.items_list ALTER COLUMN price TYPE numeric(10,2);
-- ALTER TABLE public.application_items ALTER COLUMN unit_price TYPE numeric(10,2);
-- ALTER TABLE public.application_items ALTER COLUMN subtotal TYPE numeric(10,2);
-- =========================================================================

-- 1. 建立商品主檔資料表 (items_list)
-- 💡 【歷史商品表更新指令】若您的商品表已存在，請在 SQL Editor 執行以下指令更新欄位：
-- ALTER TABLE public.items_list ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
CREATE TABLE IF NOT EXISTS public.items_list (
    item_id text PRIMARY KEY,
    item_name text NOT NULL,
    inventory integer NOT NULL DEFAULT 0,
    price numeric(10,2) NOT NULL DEFAULT 0.00,
    image text,
    is_active boolean NOT NULL DEFAULT true
);

-- 2. 建立申請主檔資料表 (applications)
CREATE TABLE IF NOT EXISTS public.applications (
    task_id text PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    applicant_name text NOT NULL,
    staff_id text NOT NULL,
    status text NOT NULL DEFAULT 'SUBMITTED',
    applicant_phone text NOT NULL,
    applicant_email text NOT NULL,
    department text NOT NULL,
    cost_center text NOT NULL,
    reason text NOT NULL,
    total_amount numeric NOT NULL DEFAULT 0,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    reviewer text,
    review_comment text
);

-- 3. 建立申請明細資料表 (application_items)
CREATE TABLE IF NOT EXISTS public.application_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id text REFERENCES public.applications(task_id) ON DELETE CASCADE NOT NULL,
    item_id text NOT NULL,
    item_name text NOT NULL,
    unit_price numeric(10,2) NOT NULL DEFAULT 0.00,
    quantity integer NOT NULL DEFAULT 0,
    subtotal numeric(10,2) NOT NULL DEFAULT 0.00
);

-- 4. 建立庫存扣減 RPC 函數 (處理後台手動修改等防呆)
CREATE OR REPLACE FUNCTION public.decrease_inventory(item_ids text[], quantities integer[])
RETURNS void AS $$
DECLARE
    i integer;
BEGIN
    FOR i IN 1..array_length(item_ids, 1) LOOP
        -- 扣減庫存
        UPDATE public.items_list
        SET inventory = inventory - quantities[i]
        WHERE item_id = item_ids[i];
        
        -- 檢查是否庫存不足扣至負數，如果是則拋出異常阻斷交易
        IF EXISTS (SELECT 1 FROM public.items_list WHERE item_id = item_ids[i] AND inventory < 0) THEN
            RAISE EXCEPTION '商品 ID % 庫存不足，無法扣減！', item_ids[i];
        END IF;
    END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4-2. 建立原子性訂單提交 RPC 函數 (前台專用，主檔、明細與庫存扣減一鍵完成，確保交易完整性)
CREATE OR REPLACE FUNCTION public.create_promo_application(
    p_task_id text,
    p_applicant_name text,
    p_staff_id text,
    p_phone text,
    p_email text,
    p_department text,
    p_cost_center text,
    p_reason text,
    p_total_amount numeric,
    p_item_ids text[],
    p_item_names text[],
    p_prices numeric[],
    p_quantities integer[]
)
RETURNS void AS $$
DECLARE
    i integer;
BEGIN
    -- 設定 session 變數以供庫存日誌觸發器讀取
    PERFORM set_config('my.app.operator', 'system', true);
    PERFORM set_config('my.app.reference_id', p_task_id, true);

    -- 1. 新增申請主檔
    INSERT INTO public.applications (
        task_id, applicant_name, staff_id, status, applicant_phone, 
        applicant_email, department, cost_center, reason, total_amount
    ) VALUES (
        p_task_id, p_applicant_name, p_staff_id, 'SUBMITTED', p_phone, 
        p_email, p_department, p_cost_center, p_reason, p_total_amount
    );

    -- 2. 迴圈寫入明細並扣減庫存
    FOR i IN 1..array_length(p_item_ids, 1) LOOP
        -- 寫入明細
        INSERT INTO public.application_items (
            task_id, item_id, item_name, unit_price, quantity, subtotal
        ) VALUES (
            p_task_id, p_item_ids[i], p_item_names[i], p_prices[i], p_quantities[i], p_prices[i] * p_quantities[i]
        );

        -- 扣減庫存
        UPDATE public.items_list
        SET inventory = inventory - p_quantities[i]
        WHERE item_id = p_item_ids[i];
        
        -- 檢查庫存是否不足
        IF EXISTS (SELECT 1 FROM public.items_list WHERE item_id = p_item_ids[i] AND inventory < 0) THEN
            RAISE EXCEPTION '商品「%」目前庫存不足！', p_item_names[i];
        END IF;
    END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4-3. 建立刪除申請明細時自動回補庫存的觸發器 (Trigger)
CREATE OR REPLACE FUNCTION public.restore_inventory_on_delete()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public.items_list
    SET inventory = inventory + OLD.quantity
    WHERE item_id = OLD.item_id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS tr_restore_inventory_on_delete ON public.application_items;
CREATE TRIGGER tr_restore_inventory_on_delete
AFTER DELETE ON public.application_items
FOR EACH ROW
EXECUTE FUNCTION public.restore_inventory_on_delete();


-- 5. 啟用資料表資料列層級安全性 (RLS) - 可選，建議啟用
ALTER TABLE public.items_list ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.application_items ENABLE ROW LEVEL SECURITY;

-- 建立允許匿名存取的安全原則 (Policies)
-- 5-1. 商品表：允許所有人讀取，允許所有人修改（前台扣庫存，後台修改商品）
DROP POLICY IF EXISTS "Allow public read" ON public.items_list;
DROP POLICY IF EXISTS "Allow public insert" ON public.items_list;
DROP POLICY IF EXISTS "Allow public update" ON public.items_list;
DROP POLICY IF EXISTS "Allow public delete" ON public.items_list;
CREATE POLICY "Allow public read" ON public.items_list FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.items_list FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.items_list FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.items_list FOR DELETE USING (true);

-- 5-2. 申請單主表：允許所有人寫入、所有人讀取（前台查詢與後台管理），允許更新與刪除
DROP POLICY IF EXISTS "Allow public select" ON public.applications;
DROP POLICY IF EXISTS "Allow public insert" ON public.applications;
DROP POLICY IF EXISTS "Allow public update" ON public.applications;
DROP POLICY IF EXISTS "Allow public delete" ON public.applications;
CREATE POLICY "Allow public select" ON public.applications FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.applications FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.applications FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.applications FOR DELETE USING (true);

-- 5-3. 申請明細表：允許所有人寫入、讀取、更新、刪除
DROP POLICY IF EXISTS "Allow public select" ON public.application_items;
DROP POLICY IF EXISTS "Allow public insert" ON public.application_items;
DROP POLICY IF EXISTS "Allow public update" ON public.application_items;
DROP POLICY IF EXISTS "Allow public delete" ON public.application_items;
CREATE POLICY "Allow public select" ON public.application_items FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.application_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.application_items FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.application_items FOR DELETE USING (true);

-- 6. 預塞部分商品測試資料 (可依需求刪除或執行)
INSERT INTO public.items_list (item_id, item_name, inventory, price, image) VALUES
('ID-001', '特製帆布袋', 50, 150, 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=300'),
('ID-002', '保溫隨行杯', 8, 350, 'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?auto=format&fit=crop&q=80&w=300'),
('ID-003', '質感原子筆', 120, 35, 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&q=80&w=300')
ON CONFLICT (item_id) DO NOTHING;

-- =========================================================================
-- 7. 後台管理員帳密與安全驗證系統 (Bcrypt 強度雜湊加密)
-- =========================================================================

-- 7-1. 先行刪除舊函數與表格更新（避免參數衝突）
DROP FUNCTION IF EXISTS public.verify_admin_login(text, text);
DROP FUNCTION IF EXISTS public.register_admin_account(text, text);
DROP FUNCTION IF EXISTS public.register_admin_account(text, text, text, text);
DROP FUNCTION IF EXISTS public.register_admin_account(text, text, text, text, text);
DROP FUNCTION IF EXISTS public.get_admin_accounts();
DROP FUNCTION IF EXISTS public.update_admin_status(text, boolean);
DROP FUNCTION IF EXISTS public.delete_admin_account(text);

-- 💡 【歷史帳號表更新指令】若您的帳號表已存在，請在 SQL Editor 執行以下指令更新欄位：
-- ALTER TABLE public.admin_accounts ADD COLUMN IF NOT EXISTS full_name text;
-- ALTER TABLE public.admin_accounts ADD COLUMN IF NOT EXISTS staff_id text;
-- ALTER TABLE public.admin_accounts ADD COLUMN IF NOT EXISTS email text;

-- 7-2. 建立管理員資料表 (is_active 預設為 false 待審核)
CREATE TABLE IF NOT EXISTS public.admin_accounts (
    username text PRIMARY KEY,
    password_hash text NOT NULL,
    full_name text,
    staff_id text,
    email text,
    is_active boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 7-3. 啟用 RLS 保護 (不對公眾開放直接讀取)
ALTER TABLE public.admin_accounts ENABLE ROW LEVEL SECURITY;

-- 7-4. 建立安全登入比對函數 (verify_admin_login)
-- 回傳代碼: 0 = 帳密錯誤, 1 = 登入成功(已啟用), 2 = 審核中(未啟用)
CREATE OR REPLACE FUNCTION public.verify_admin_login(p_username text, p_password text)
RETURNS integer AS $$
DECLARE
    v_hash text;
    v_active boolean;
BEGIN
    SELECT password_hash, is_active INTO v_hash, v_active 
    FROM public.admin_accounts 
    WHERE username = p_username;
    
    -- 帳密錯誤
    IF v_hash IS NULL OR v_hash <> crypt(p_password, v_hash) THEN
        RETURN 0; 
    END IF;
    
    -- 已啟用
    IF v_active THEN
        RETURN 1;
    -- 審核中
    ELSE
        RETURN 2;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7-5. 建立管理員安全註冊函數 (register_admin_account)
-- 回傳代碼: 0 = 帳號已存在, 1 = 註冊成功待審核
CREATE OR REPLACE FUNCTION public.register_admin_account(p_username text, p_password text, p_full_name text, p_staff_id text, p_email text)
RETURNS integer AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.admin_accounts WHERE username = p_username) THEN
        RETURN 0;
    END IF;

    INSERT INTO public.admin_accounts (username, password_hash, full_name, staff_id, email, is_active)
    VALUES (p_username, crypt(p_password, gen_salt('bf')), p_full_name, p_staff_id, p_email, false);
    
    RETURN 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7-6. 建立帳號後台管理函數 (超級管理員專用 API)
CREATE OR REPLACE FUNCTION public.get_admin_accounts()
RETURNS TABLE (username text, full_name text, staff_id text, email text, is_active boolean, created_at timestamp with time zone) AS $$
BEGIN
    RETURN QUERY SELECT a.username, a.full_name, a.staff_id, a.email, a.is_active, a.created_at 
    FROM public.admin_accounts a 
    ORDER BY a.created_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.update_admin_status(p_username text, p_is_active boolean)
RETURNS void AS $$
BEGIN
    UPDATE public.admin_accounts SET is_active = p_is_active WHERE username = p_username;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.delete_admin_account(p_username text)
RETURNS void AS $$
BEGIN
    DELETE FROM public.admin_accounts WHERE username = p_username;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7-7. 預塞預設已啟用的超級管理員 (帳號: admin / 密碼: admin1234)
INSERT INTO public.admin_accounts (username, password_hash, full_name, staff_id, email, is_active)
VALUES ('admin', crypt('admin1234', gen_salt('bf')), '系統管理員', 'ADMIN-01', 'admin@example.com', true)
ON CONFLICT (username) DO UPDATE SET is_active = true, full_name = '系統管理員', staff_id = 'ADMIN-01', email = 'admin@example.com';

-- =========================================================================
-- 8. Supabase Storage 儲存桶與安全原則設定 (商品圖片上傳用)
-- =========================================================================

-- 8-1. 建立名為 product-images 的公開 (Public) 儲存桶
INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO NOTHING;

-- 8-2. 建立儲存桶檔案的安全存取原則 (RLS Policies)
-- 允許所有人（包含匿名與一般訪客）讀取與下載儲存桶中的圖片
DROP POLICY IF EXISTS "Allow public select" ON storage.objects;
CREATE POLICY "Allow public select" ON storage.objects
FOR SELECT USING (bucket_id = 'product-images');

-- 允許任何人（包含匿名與一般訪客）上傳檔案至儲存桶
DROP POLICY IF EXISTS "Allow public insert" ON storage.objects;
CREATE POLICY "Allow public insert" ON storage.objects
FOR INSERT WITH CHECK (bucket_id = 'product-images');

-- 允許任何人（包含匿名與一般訪客）更新與覆寫儲存桶內的檔案
DROP POLICY IF EXISTS "Allow public update" ON storage.objects;
CREATE POLICY "Allow public update" ON storage.objects
FOR UPDATE USING (bucket_id = 'product-images');

-- 允許任何人（包含匿名與一般訪客）刪除儲存桶內的檔案 (可選)
DROP POLICY IF EXISTS "Allow public delete" ON storage.objects;
CREATE POLICY "Allow public delete" ON storage.objects
FOR DELETE USING (bucket_id = 'product-images');

-- 9-1. 先行刪除舊函數與表格更新
DROP FUNCTION IF EXISTS public.get_inventory_logs();
DROP FUNCTION IF EXISTS public.update_inventory_manual(text, integer, text);
DROP FUNCTION IF EXISTS public.delete_application_by_admin(text, text);
DROP FUNCTION IF EXISTS public.update_product_active_status(text, boolean, text);

-- 9-2. 建立庫存異動紀錄表
CREATE TABLE IF NOT EXISTS public.inventory_logs (
    log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id text NOT NULL,
    item_name text NOT NULL,
    change_type text NOT NULL, -- 'ORDER_SUBMIT', 'ORDER_DELETE', 'MANUAL_ADJUST', 'PRODUCT_LIST', 'PRODUCT_DELIST'
    change_qty integer NOT NULL,
    old_qty integer NOT NULL,
    new_qty integer NOT NULL,
    reference_id text, -- 關聯的訂單單號或操作來源
    operator text DEFAULT 'system' NOT NULL, -- 變更操作人員 (如: system, admin)
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 9-2. 啟用 RLS 保護 (不對外開放直接查詢)
ALTER TABLE public.inventory_logs ENABLE ROW LEVEL SECURITY;

-- 9-3. 建立變更監聽觸發器函數 (log_inventory_changes)
CREATE OR REPLACE FUNCTION public.log_inventory_changes()
RETURNS TRIGGER AS $$
DECLARE
    v_change_qty integer;
    v_change_type text := 'MANUAL_ADJUST';
    v_ref_id text := NULL;
    v_operator text := 'system';
BEGIN
    -- 試圖從 session 變數中讀取操作人員及參考單號 (設定方式如: SET LOCAL my.app.operator = 'admin')
    BEGIN
        v_operator := current_setting('my.app.operator', true);
        IF v_operator IS NULL OR v_operator = '' THEN
            v_operator := 'system';
        END IF;
    EXCEPTION WHEN OTHERS THEN
        v_operator := 'system';
    END;

    BEGIN
        v_ref_id := current_setting('my.app.reference_id', true);
    EXCEPTION WHEN OTHERS THEN
        v_ref_id := NULL;
    END;

    -- 1. 檢查上下架狀態變更
    IF OLD.is_active IS DISTINCT FROM NEW.is_active THEN
        IF NEW.is_active = true THEN
            v_change_type := 'PRODUCT_LIST';
        ELSE
            v_change_type := 'PRODUCT_DELIST';
        END IF;
        
        INSERT INTO public.inventory_logs (
            item_id, item_name, change_type, change_qty, old_qty, new_qty, reference_id, operator
        ) VALUES (
            NEW.item_id, NEW.item_name, v_change_type, 0, OLD.inventory, NEW.inventory, v_ref_id, v_operator
        );
    END IF;

    -- 2. 檢查庫存數量變更
    v_change_qty := NEW.inventory - OLD.inventory;
    IF v_change_qty <> 0 THEN
        IF v_operator = 'system' THEN
            IF v_change_qty < 0 THEN
                v_change_type := 'ORDER_SUBMIT';
            ELSE
                v_change_type := 'ORDER_DELETE';
            END IF;
        ELSE
            -- 若為管理員操作，且非系統預設，可由 reference_id 判別，否則為 MANUAL_ADJUST
            IF v_ref_id IS NOT NULL AND v_ref_id <> '' AND v_ref_id <> 'MANUAL_ADJUST' THEN
                v_change_type := v_ref_id;
            ELSE
                v_change_type := 'MANUAL_ADJUST';
            END IF;
        END IF;

        INSERT INTO public.inventory_logs (
            item_id, item_name, change_type, change_qty, old_qty, new_qty, reference_id, operator
        ) VALUES (
            NEW.item_id, NEW.item_name, v_change_type, v_change_qty, OLD.inventory, NEW.inventory, v_ref_id, v_operator
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 9-4. 建立觸發器
DROP TRIGGER IF EXISTS tr_log_inventory_changes ON public.items_list;
CREATE TRIGGER tr_log_inventory_changes
AFTER UPDATE OF inventory, is_active ON public.items_list
FOR EACH ROW
EXECUTE FUNCTION public.log_inventory_changes();

-- 9-5. 建立查詢日誌的 RPC 函數 (限管理員存取)
CREATE OR REPLACE FUNCTION public.get_inventory_logs()
RETURNS TABLE (
    log_id bigint,
    item_id text,
    item_name text,
    change_type text,
    change_qty integer,
    old_qty integer,
    new_qty integer,
    reference_id text,
    operator text,
    created_at timestamp with time zone
) AS $$
BEGIN
    RETURN QUERY SELECT 
        l.log_id, l.item_id, l.item_name, l.change_type, l.change_qty, 
        l.old_qty, l.new_qty, l.reference_id, l.operator, l.created_at
    FROM public.inventory_logs l
    ORDER BY l.created_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 9-6. 建立管理員手動調整庫存的安全 RPC 函數
CREATE OR REPLACE FUNCTION public.update_inventory_manual(p_item_id text, p_new_qty integer, p_operator text)
RETURNS void AS $$
BEGIN
    -- 設定交易 Session 變數，以便讓觸發器知道是哪位管理員改的
    PERFORM set_config('my.app.operator', p_operator, true);
    PERFORM set_config('my.app.reference_id', 'MANUAL_ADJUST', true);
    
    UPDATE public.items_list
    SET inventory = p_new_qty
    WHERE item_id = p_item_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 9-7. 建立管理員刪除申請單的安全 RPC 函數 (觸發庫存回補日誌)
CREATE OR REPLACE FUNCTION public.delete_application_by_admin(p_task_id text, p_operator text)
RETURNS void AS $$
BEGIN
    -- 設定交易 Session 變數，讓刪除回補明細時，觸發器能記下操作的管理員與單號
    PERFORM set_config('my.app.operator', p_operator, true);
    PERFORM set_config('my.app.reference_id', p_task_id, true);
    
    DELETE FROM public.applications
    WHERE task_id = p_task_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 9-8. 建立管理員調整商品上下架狀態的安全 RPC 函數
CREATE OR REPLACE FUNCTION public.update_product_active_status(p_item_id text, p_is_active boolean, p_operator text)
RETURNS void AS $$
BEGIN
    -- 設定交易 Session 變數，以便讓觸發器知道是哪位管理員改的
    PERFORM set_config('my.app.operator', p_operator, true);
    IF p_is_active = true THEN
        PERFORM set_config('my.app.reference_id', 'PRODUCT_LIST', true);
    ELSE
        PERFORM set_config('my.app.reference_id', 'PRODUCT_DELIST', true);
    END IF;
    
    UPDATE public.items_list
    SET is_active = p_is_active
    WHERE item_id = p_item_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 9-9. 自動補檔腳本：為現有商品補齊「商品上架」的庫存日誌紀錄
INSERT INTO public.inventory_logs (
    item_id, item_name, change_type, change_qty, old_qty, new_qty, reference_id, operator, created_at
)
SELECT 
    item_id, 
    item_name, 
    'PRODUCT_LIST', 
    0, 
    inventory, 
    inventory, 
    'BACKFILL', 
    'system', 
    now()
FROM public.items_list i
WHERE NOT EXISTS (
    SELECT 1 
    FROM public.inventory_logs l 
    WHERE l.item_id = i.item_id AND l.change_type = 'PRODUCT_LIST'
);
